import ActionButton from "./ActionButton";

const tableRow = [
  {
    condition: "accepted-cases",
    id: "11",
    priority: "low",
    caseName: "case number 11",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Clinical chemistry",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "rejected-cases",
    id: "21",
    priority: "medium",
    caseName: "case number 21",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Molecular diagnostics",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "pending-cases",
    id: "31",
    priority: "high",
    caseName: "case number 31",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Urinalysis",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "accepted-cases",
    id: "12",
    priority: "low",
    caseName: "case number 12",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Clinical chemistry",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "rejected-cases",
    id: "22",
    priority: "medium",
    caseName: "case number 22",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Molecular diagnostics",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "pending-cases",
    id: "32",
    priority: "high",
    caseName: "case number 32",
    assignee: "Jane Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Urinalysis",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "accepted-cases",
    id: "11",
    priority: "low",
    caseName: "case number 11",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Clinical chemistry",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "rejected-cases",
    id: "21",
    priority: "medium",
    caseName: "case number 21",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Molecular diagnostics",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "pending-cases",
    id: "31",
    priority: "high",
    caseName: "case number 31",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Urinalysis",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "accepted-cases",
    id: "12",
    priority: "low",
    caseName: "case number 12",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Clinical chemistry",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "rejected-cases",
    id: "22",
    priority: "medium",
    caseName: "case number 22",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Molecular diagnostics",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "pending-cases",
    id: "32",
    priority: "high",
    caseName: "case number 32",
    assignee: "Jane Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Urinalysis",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "accepted-cases",
    id: "11",
    priority: "low",
    caseName: "case number 11",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Clinical chemistry",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "rejected-cases",
    id: "21",
    priority: "medium",
    caseName: "case number 21",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Molecular diagnostics",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "pending-cases",
    id: "31",
    priority: "high",
    caseName: "case number 31",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Urinalysis",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "accepted-cases",
    id: "12",
    priority: "low",
    caseName: "case number 12",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Clinical chemistry",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "rejected-cases",
    id: "22",
    priority: "medium",
    caseName: "case number 22",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Molecular diagnostics",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "pending-cases",
    id: "32",
    priority: "high",
    caseName: "case number 32",
    assignee: "Jane Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Urinalysis",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "accepted-cases",
    id: "11",
    priority: "low",
    caseName: "case number 11",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Clinical chemistry",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "rejected-cases",
    id: "21",
    priority: "medium",
    caseName: "case number 21",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Molecular diagnostics",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "pending-cases",
    id: "31",
    priority: "high",
    caseName: "case number 31",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Urinalysis",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "accepted-cases",
    id: "12",
    priority: "low",
    caseName: "case number 12",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Clinical chemistry",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "rejected-cases",
    id: "22",
    priority: "medium",
    caseName: "case number 22",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Molecular diagnostics",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "pending-cases",
    id: "32",
    priority: "high",
    caseName: "case number 32",
    assignee: "Jane Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Urinalysis",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "accepted-cases",
    id: "11",
    priority: "low",
    caseName: "case number 11",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Clinical chemistry",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "rejected-cases",
    id: "21",
    priority: "medium",
    caseName: "case number 21",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Molecular diagnostics",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "pending-cases",
    id: "31",
    priority: "high",
    caseName: "case number 31",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Urinalysis",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "accepted-cases",
    id: "12",
    priority: "low",
    caseName: "case number 12",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Clinical chemistry",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "rejected-cases",
    id: "22",
    priority: "medium",
    caseName: "case number 22",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Molecular diagnostics",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "pending-cases",
    id: "32",
    priority: "high",
    caseName: "case number 32",
    assignee: "Jane Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Urinalysis",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "accepted-cases",
    id: "11",
    priority: "low",
    caseName: "case number 11",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Clinical chemistry",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "rejected-cases",
    id: "21",
    priority: "medium",
    caseName: "case number 21",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Molecular diagnostics",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "pending-cases",
    id: "31",
    priority: "high",
    caseName: "case number 31",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Urinalysis",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "accepted-cases",
    id: "12",
    priority: "low",
    caseName: "case number 12",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Clinical chemistry",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "rejected-cases",
    id: "22",
    priority: "medium",
    caseName: "case number 22",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Molecular diagnostics",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "pending-cases",
    id: "32",
    priority: "high",
    caseName: "case number 32",
    assignee: "Jane Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Urinalysis",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "accepted-cases",
    id: "11",
    priority: "low",
    caseName: "case number 11",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Clinical chemistry",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "rejected-cases",
    id: "21",
    priority: "medium",
    caseName: "case number 21",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Molecular diagnostics",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "pending-cases",
    id: "31",
    priority: "high",
    caseName: "case number 31",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Urinalysis",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "accepted-cases",
    id: "12",
    priority: "low",
    caseName: "case number 12",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Clinical chemistry",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "rejected-cases",
    id: "22",
    priority: "medium",
    caseName: "case number 22",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Molecular diagnostics",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "pending-cases",
    id: "32",
    priority: "high",
    caseName: "case number 32",
    assignee: "Jane Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Urinalysis",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "accepted-cases",
    id: "11",
    priority: "low",
    caseName: "case number 11",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Clinical chemistry",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "rejected-cases",
    id: "21",
    priority: "medium",
    caseName: "case number 21",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Molecular diagnostics",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "pending-cases",
    id: "31",
    priority: "high",
    caseName: "case number 31",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Urinalysis",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "accepted-cases",
    id: "12",
    priority: "low",
    caseName: "case number 12",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Clinical chemistry",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "rejected-cases",
    id: "22",
    priority: "medium",
    caseName: "case number 22",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Molecular diagnostics",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "pending-cases",
    id: "32",
    priority: "high",
    caseName: "case number 32",
    assignee: "Jane Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Urinalysis",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "accepted-cases",
    id: "11",
    priority: "low",
    caseName: "case number 11",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Clinical chemistry",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "rejected-cases",
    id: "21",
    priority: "medium",
    caseName: "case number 21",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Molecular diagnostics",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "pending-cases",
    id: "31",
    priority: "high",
    caseName: "case number 31",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Urinalysis",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "accepted-cases",
    id: "12",
    priority: "low",
    caseName: "case number 12",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Clinical chemistry",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "rejected-cases",
    id: "22",
    priority: "medium",
    caseName: "case number 22",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Molecular diagnostics",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "pending-cases",
    id: "32",
    priority: "high",
    caseName: "case number 32",
    assignee: "Jane Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Urinalysis",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "accepted-cases",
    id: "11",
    priority: "low",
    caseName: "case number 11",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Clinical chemistry",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "rejected-cases",
    id: "21",
    priority: "medium",
    caseName: "case number 21",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Molecular diagnostics",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "pending-cases",
    id: "31",
    priority: "high",
    caseName: "case number 31",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Urinalysis",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "accepted-cases",
    id: "12",
    priority: "low",
    caseName: "case number 12",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Clinical chemistry",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "rejected-cases",
    id: "22",
    priority: "medium",
    caseName: "case number 22",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Molecular diagnostics",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "pending-cases",
    id: "32",
    priority: "high",
    caseName: "case number 32",
    assignee: "Jane Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Urinalysis",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "accepted-cases",
    id: "11",
    priority: "low",
    caseName: "case number 11",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Clinical chemistry",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "rejected-cases",
    id: "21",
    priority: "medium",
    caseName: "case number 21",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Molecular diagnostics",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "pending-cases",
    id: "31",
    priority: "high",
    caseName: "case number 31",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Urinalysis",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "accepted-cases",
    id: "12",
    priority: "low",
    caseName: "case number 12",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Clinical chemistry",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "rejected-cases",
    id: "22",
    priority: "medium",
    caseName: "case number 22",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Molecular diagnostics",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "pending-cases",
    id: "32",
    priority: "high",
    caseName: "case number 32",
    assignee: "Jane Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Urinalysis",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "accepted-cases",
    id: "11",
    priority: "low",
    caseName: "case number 11",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Clinical chemistry",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "rejected-cases",
    id: "21",
    priority: "medium",
    caseName: "case number 21",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Molecular diagnostics",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "pending-cases",
    id: "31",
    priority: "high",
    caseName: "case number 31",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Urinalysis",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "accepted-cases",
    id: "12",
    priority: "low",
    caseName: "case number 12",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Clinical chemistry",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "rejected-cases",
    id: "22",
    priority: "medium",
    caseName: "case number 22",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Molecular diagnostics",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "pending-cases",
    id: "32",
    priority: "high",
    caseName: "case number 32",
    assignee: "Jane Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Urinalysis",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "accepted-cases",
    id: "11",
    priority: "low",
    caseName: "case number 11",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Clinical chemistry",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "rejected-cases",
    id: "21",
    priority: "medium",
    caseName: "case number 21",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Molecular diagnostics",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "pending-cases",
    id: "31",
    priority: "high",
    caseName: "case number 31",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Urinalysis",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "accepted-cases",
    id: "12",
    priority: "low",
    caseName: "case number 12",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Clinical chemistry",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "rejected-cases",
    id: "22",
    priority: "medium",
    caseName: "case number 22",
    assignee: "John Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Molecular diagnostics",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  {
    condition: "pending-cases",
    id: "32",
    priority: "high",
    caseName: "case number 32",
    assignee: "Jane Doe",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    status: "In Progress",
    type: "Urinalysis",
    dateCreated: "02/06/2024",
    lastUpdated: "03/06/2024",
    action: <ActionButton />
  },
  
];

export default tableRow;